package httpapi

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	"groopx/backend/internal/config"
)

func Register(router *gin.Engine, database *pgxpool.Pool, configuration config.Config) {
	db = database
	cfg = configuration
	initializePush()
	registerAdminRoutes(router)
	v1 := router.Group("/api/v1")
	v1.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok", "service": "groopx-api"})
	})
	v1.POST("/auth/request-otp", requestOTP)
	v1.POST("/auth/verify-otp", verifyOTP)
	v1.POST("/auth/refresh", refreshSession)
	v1.POST("/auth/logout", logout)
	v1.GET("/users/me", requireBearer(), getCurrentUser)
	v1.POST("/users/me/sessions", requireBearer(), listSessions)
	v1.DELETE("/users/me/sessions/:id", requireBearer(), revokeSession)
	v1.POST("/users/me/sessions/revoke-others", requireBearer(), revokeOtherSessions)
	v1.PUT("/users/me/profile", requireBearer(), updateProfile)
	v1.PUT("/users/me/avatar", requireBearer(), updateAvatar)
	v1.DELETE("/users/me/avatar", requireBearer(), removeAvatar)
	v1.PATCH("/users/me/settings", requireBearer(), updateSettings)
	v1.GET("/users/blocked", requireBearer(), listBlockedUsers)
	v1.POST("/users/:id/block", requireBearer(), blockUser)
	v1.DELETE("/users/:id/block", requireBearer(), unblockUser)
	v1.POST("/users/:id/report", requireBearer(), reportUser)
	v1.GET("/ws", chatSocket)
	v1.GET("/conversations", requireBearer(), listConversations)
	v1.POST("/conversations", requireBearer(), createConversation)
	v1.GET("/conversations/:id", requireBearer(), getConversationDetails)
	v1.GET("/conversations/:id/messages", requireBearer(), listMessages)
	v1.GET("/conversations/:id/messages/search", requireBearer(), searchMessages)
	v1.GET("/conversations/:id/media", requireBearer(), listConversationMedia)
	v1.POST("/conversations/:id/read", requireBearer(), markConversationRead)
	v1.PATCH("/messages/:id", requireBearer(), editMessage)
	v1.DELETE("/messages/:id", requireBearer(), deleteMessage)
	v1.POST("/messages/:id/reactions", requireBearer(), addReaction)
	v1.DELETE("/messages/:id/reactions", requireBearer(), removeReaction)
	v1.POST("/contacts", requireBearer(), createContact)
	v1.GET("/contacts", requireBearer(), listContacts)
	v1.GET("/users/search", requireBearer(), searchUsers)
	v1.POST("/groups", requireBearer(), createGroup)
	v1.GET("/groups/:id", requireBearer(), getGroup)
	v1.PATCH("/groups/:id", requireBearer(), updateGroup)
	v1.POST("/groups/:id/members", requireBearer(), addGroupMembers)
	v1.DELETE("/groups/:id/members/:userId", requireBearer(), removeGroupMember)
	v1.PATCH("/groups/:id/members/:userId/role", requireBearer(), updateGroupMemberRole)
	v1.POST("/groups/:id/invites", requireBearer(), createGroupInvite)
	v1.POST("/group-invites/:token/join", requireBearer(), joinGroupInvite)
	v1.POST("/groups/:id/leave", requireBearer(), leaveGroup)
	v1.GET("/communities", requireBearer(), listCommunities)
	v1.GET("/manageable-groups", requireBearer(), listManageableGroups)
	v1.POST("/communities", requireBearer(), createCommunity)
	v1.GET("/communities/:id", requireBearer(), getCommunity)
	v1.POST("/communities/:id/groups", requireBearer(), addCommunityGroup)
	v1.DELETE("/communities/:id/groups/:groupId", requireBearer(), removeCommunityGroup)
	v1.POST("/conversations/:id/archive", requireBearer(), setArchive(true))
	v1.DELETE("/conversations/:id/archive", requireBearer(), setArchive(false))
	v1.DELETE("/conversations/:id", requireBearer(), deleteConversation)
	v1.PATCH("/conversations/:id/preferences", requireBearer(), updateConversationPreferences)
	v1.POST("/media/presign", requireBearer(), presignMedia)
	v1.POST("/media/complete", requireBearer(), completeMediaMessage)
	v1.GET("/statuses", requireBearer(), listStatuses)
	v1.POST("/statuses", requireBearer(), createStatus)
	v1.POST("/statuses/:id/view", requireBearer(), viewStatus)
	v1.DELETE("/statuses/:id", requireBearer(), deleteStatus)
	v1.GET("/reminders", requireBearer(), listReminders)
	v1.POST("/reminders", requireBearer(), createReminder)
	v1.PATCH("/reminders/:id", requireBearer(), updateReminder)
	v1.DELETE("/reminders/:id", requireBearer(), deleteReminder)
	v1.POST("/devices", requireBearer(), registerDevice)
	v1.DELETE("/devices", requireBearer(), unregisterDevice)
	v1.GET("/notifications", requireBearer(), listNotifications)
	v1.POST("/notifications/read-all", requireBearer(), markAllNotificationsRead)
	v1.POST("/notifications/:id/read", requireBearer(), markNotificationRead)
	v1.POST("/calls/token", requireBearer(), createCallToken)
	v1.GET("/calls", requireBearer(), listCalls)
	v1.POST("/calls/:id/join", requireBearer(), joinCall)
	v1.POST("/calls/:id/decline", requireBearer(), declineCall)
	v1.POST("/calls/:id/end", requireBearer(), endCall)
}
