const API='/admin/api';
const state={token:sessionStorage.getItem('groopx_admin_token')||'',page:'dashboard',pageNo:1,filters:{}};
const $=s=>document.querySelector(s);const content=$('#content');
const titles={dashboard:'Dashboard overview',users:'User management',groups:'Groups & communities',conversations:'Conversation activity',reports:'Safety reports',calls:'Call activity',announcements:'Announcements',system:'System status',audit:'Administrator audit logs'};

async function request(path,options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{}) ,...options.headers}});const data=response.status===204?{}:await response.json().catch(()=>({}));if(response.status===401){logout();throw new Error('Session expired');}if(!response.ok)throw new Error(data.error||'Request failed');return data}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v,withTime=true){if(!v)return'—';const d=new Date(v);return new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})}).format(d)}
function initials(v='G'){return v.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'G'}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function status(value){return `<span class="status status-${escapeHtml(value)}">${escapeHtml(value)}</span>`}
function loading(){content.innerHTML='<div class="panel loading">Loading GroopX data…</div>'}
function errorView(error){content.innerHTML=`<div class="panel empty"><h3>Could not load this section</h3><p>${escapeHtml(error.message)}</p><button class="action-button" onclick="loadPage()">Retry</button></div>`}

$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';const button=event.currentTarget.querySelector('button');button.disabled=true;try{const data=await request('/login',{method:'POST',body:JSON.stringify({email:$('#email').value.trim(),password:$('#password').value})});state.token=data.access_token;sessionStorage.setItem('groopx_admin_token',state.token);showApp(data.admin)}catch(error){$('#loginError').textContent=error.message}finally{button.disabled=false}});
$('#logoutButton').addEventListener('click',logout);$('#refreshButton').addEventListener('click',()=>loadPage());$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#nav').addEventListener('click',event=>{const button=event.target.closest('button[data-page]');if(!button)return;state.page=button.dataset.page;state.pageNo=1;state.filters={};document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===button));$('#sidebar').classList.remove('open');loadPage()});
function logout(){state.token='';sessionStorage.removeItem('groopx_admin_token');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#password').value=''}
async function showApp(admin){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');try{const me=admin||await request('/me');$('#adminEmail').textContent=me.email}catch{return logout()}loadPage()}
async function loadPage(){loading();$('#pageTitle').textContent=titles[state.page];try{if(state.page==='dashboard')await dashboard();else if(state.page==='announcements')await announcements();else if(state.page==='system')await systemStatus();else await listing(state.page)}catch(error){errorView(error)}}

async function announcements(){const data=await request('/announcements');content.innerHTML=`<div class="dashboard-grid"><article class="panel"><div class="panel-head"><div><h3>Send announcement</h3><span>Creates an in-app notification and sends FCM when configured</span></div></div><label>Title<input id="announcementTitle" maxlength="160" placeholder="Announcement title"></label><label>Message<textarea id="announcementBody" rows="5" maxlength="1000" placeholder="Write a clear message for GroopX users"></textarea></label><label>Audience<select id="announcementAudience"><option value="all">All users</option><option value="active">Active accounts only</option></select></label><button class="primary-button" onclick="sendAnnouncement()">Send announcement</button></article><article class="panel"><div class="panel-head"><div><h3>Recent announcements</h3><span>${data.total} sent</span></div></div><div class="quick-list">${data.items.length?data.items.map(x=>`<div class="quick-item"><span class="mini-icon">✦</span><div><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.body)} · ${fmtDate(x.created_at)}</small></div><b>${x.recipients}</b></div>`).join(''):'<div class="empty">No announcements sent yet</div>'}</div></article></div>`}
async function sendAnnouncement(){const title=$('#announcementTitle').value.trim(),body=$('#announcementBody').value.trim(),audience=$('#announcementAudience').value;if(!title||!body){toast('Title and message are required');return}try{const result=await request('/announcements',{method:'POST',body:JSON.stringify({title,body,audience})});toast(`Announcement sent to ${result.recipients} users`);announcements()}catch(error){toast(error.message)}}
async function systemStatus(){const data=await request('/system');const rows=[['Database',data.database,'PostgreSQL connection'],['Firebase push',data.firebase,'FCM service account'],['LiveKit calls',data.livekit,'Audio and video calling'],['Media storage',data.media_storage,'S3/R2 uploads'],['Twilio OTP',data.twilio,'Production SMS verification']];content.innerHTML=`<div class="welcome"><div><h1>Integration health</h1><p>Live server configuration without exposing private credentials.</p></div><span class="date-chip">${escapeHtml(data.environment||'development')}</span></div><div class="metric-grid">${rows.map(x=>`<article class="metric-card" style="--soft:${x[1]?'#e7f9f1':'#fff1e1'};--accent:${x[1]?'#16a36d':'#e88c1f'}"><div class="metric-icon">${x[1]?'✓':'!'}</div><p>${x[0]}</p><strong style="font-size:18px">${x[1]?'Ready':'Needs setup'}</strong><small>${x[2]}</small></article>`).join('')}</div><div class="privacy-banner">Secrets are configured through Render environment variables and are never displayed in this dashboard.</div>`}

async function dashboard(){const data=await request('/dashboard');const m=data.metrics;$('#reportBadge').textContent=m.open_reports;$('#reportBadge').classList.toggle('hidden',!m.open_reports);const cards=[['Users',m.users,'♙','#eee9ff','#6d35f4'],['Active users',m.active_users,'●','#e7f9f1','#16a36d'],['Groups',m.groups,'♟','#e8f7ff','#2585b9'],['Messages today',m.messages_today,'✦','#fff1e1','#e88c1f'],['New users today',m.new_users_today,'↗','#f3eaff','#8d58ff'],['Direct chats',m.direct_chats,'◌','#e8f8f7','#159c96'],['Open reports',m.open_reports,'⚑','#ffecef','#e34f62'],['Calls today',m.calls_today,'⌕','#edf1ff','#4d69cf']];const max=Math.max(1,...data.trend.flatMap(x=>[x.users,x.messages]));content.innerHTML=`<div class="welcome"><div><h1>Good day, Administrator</h1><p>Here’s what is happening across GroopX today.</p></div><span class="date-chip">${fmtDate(new Date(),false)}</span></div><div class="metric-grid">${cards.map(c=>`<article class="metric-card" style="--soft:${c[3]};--accent:${c[4]}"><div class="metric-icon">${c[2]}</div><p>${c[0]}</p><strong>${Number(c[1]).toLocaleString('en-IN')}</strong></article>`).join('')}</div><div class="dashboard-grid"><article class="panel"><div class="panel-head"><div><h3>7-day growth</h3><span>New users and messages</span></div><span>Live database</span></div><div class="chart">${data.trend.map(x=>`<div class="chart-column"><i class="bar bar-users" style="height:${Math.max(2,x.users/max*100)}%" title="${x.users} users"></i><i class="bar bar-messages" style="height:${Math.max(2,x.messages/max*100)}%" title="${x.messages} messages"></i><span class="chart-label">${new Date(x.day).toLocaleDateString('en',{weekday:'short'})}</span></div>`).join('')}</div><div class="legend"><span><i style="background:#b9a1ff"></i>New users</span><span><i style="background:#6d35f4"></i>Messages</span></div></article><article class="panel"><div class="panel-head"><div><h3>Quick health</h3><span>Platform overview</span></div></div><div class="quick-list">${[['Active accounts','Ready to chat',m.active_users,'♙'],['Groups & communities','Growing spaces',m.groups,'♟'],['Safety queue','Needs review',m.open_reports,'⚑'],['Calls today','Audio & video',m.calls_today,'⌕']].map(x=>`<div class="quick-item"><span class="mini-icon">${x[3]}</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div><b>${x[2]}</b></div>`).join('')}</div></article></div>`}

const configs={
 users:{path:'/users',search:true,filter:['','active','suspended','deleted'],head:['User','Phone','Joined','Last active','Chats','Status','Action'],row:x=>`<td><div class="user-cell"><span class="avatar">${initials(x.full_name||x.username)}</span><div><strong>${escapeHtml(x.full_name||'Profile pending')}</strong><small>@${escapeHtml(x.username||'not-set')}</small></div></div></td><td>${escapeHtml(x.phone)}</td><td>${fmtDate(x.created_at,false)}</td><td>${fmtDate(x.last_seen_at)}</td><td>${x.conversations}</td><td>${status(x.status)}</td><td><button class="action-button" onclick="manageUser('${encodeURIComponent(JSON.stringify(x))}')">Manage</button></td>`},
 groups:{path:'/groups',search:true,head:['Group','Privacy','Type','Members','Messages','Created'],row:x=>`<td><strong>${escapeHtml(x.title)}</strong><br><small>${escapeHtml(x.description)}</small></td><td>${status(x.privacy)}</td><td>${escapeHtml(x.kind)}</td><td>${x.members}</td><td>${x.messages}</td><td>${fmtDate(x.created_at,false)}</td>`},
 conversations:{path:'/conversations',filter:['','direct','group','community'],note:'🔒 GroopX privacy protection: administrators can see activity metadata, but private message content is not exposed.',head:['Conversation ID','Type','Title','Members','Messages','Created','Last activity'],row:x=>`<td><code>${escapeHtml(x.id.slice(0,8))}…</code></td><td>${status(x.kind)}</td><td>${escapeHtml(x.title||'Private conversation')}</td><td>${x.members}</td><td>${x.messages}</td><td>${fmtDate(x.created_at,false)}</td><td>${fmtDate(x.last_message_at)}</td>`},
 reports:{path:'/reports',filter:['','open','reviewing','resolved','dismissed'],head:['Reported user','Reporter','Reason','Details','Created','Status','Action'],row:x=>`<td><strong>${escapeHtml(x.reported_user)}</strong></td><td>${escapeHtml(x.reporter)}</td><td>${escapeHtml(x.reason)}</td><td>${escapeHtml(x.details||'—')}</td><td>${fmtDate(x.created_at)}</td><td>${status(x.status)}</td><td><button class="action-button" onclick="manageReport('${encodeURIComponent(JSON.stringify(x))}')">Review</button></td>`},
 calls:{path:'/calls',filter:['','ringing','answered','missed','declined','ended'],head:['Call ID','Initiator','Type','Participants','Started','Ended','Status'],row:x=>`<td><code>${escapeHtml(x.id.slice(0,8))}…</code></td><td>${escapeHtml(x.initiator)}</td><td>${escapeHtml(x.kind)}</td><td>${x.participants}</td><td>${fmtDate(x.started_at)}</td><td>${fmtDate(x.ended_at)}</td><td>${status(x.status)}</td>`},
 audit:{path:'/audit-logs',head:['Administrator','Action','Target','Details','Time'],row:x=>`<td>${escapeHtml(x.admin_email)}</td><td><strong>${escapeHtml(x.action)}</strong></td><td>${escapeHtml(x.target_type)} ${escapeHtml((x.target_id||'').slice(0,12))}</td><td><code>${escapeHtml(JSON.stringify(x.details))}</code></td><td>${fmtDate(x.created_at)}</td>`}
};
async function listing(name){const c=configs[name];const params=new URLSearchParams({page:state.pageNo,limit:20,...state.filters});const data=await request(`${c.path}?${params}`);const pages=Math.max(1,Math.ceil(data.total/data.limit));content.innerHTML=`${c.note?`<div class="privacy-banner">${c.note}</div>`:''}<div class="toolbar">${c.search?`<input class="search" id="tableSearch" value="${escapeHtml(state.filters.q||'')}" placeholder="Search ${name}…">`:''}${c.filter?`<select id="tableFilter">${c.filter.map(v=>`<option value="${v}" ${state.filters[name==='conversations'?'kind':'status']===v?'selected':''}>${v||'All '+name}</option>`).join('')}</select>`:''}<span style="margin-left:auto;font-size:11px;color:var(--muted)">${data.total.toLocaleString('en-IN')} records</span></div><div class="table-panel"><table><thead><tr>${c.head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${data.items.length?data.items.map(x=>`<tr>${c.row(x)}</tr>`).join(''):`<tr><td colspan="${c.head.length}" class="empty">No matching records</td></tr>`}</tbody></table><div class="pagination"><button ${state.pageNo<=1?'disabled':''} onclick="changePage(-1)">← Previous</button><span>Page ${state.pageNo} of ${pages}</span><button ${state.pageNo>=pages?'disabled':''} onclick="changePage(1)">Next →</button></div></div>`;let timer;if($('#tableSearch'))$('#tableSearch').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.filters.q=e.target.value.trim();state.pageNo=1;listing(name)},350)});if($('#tableFilter'))$('#tableFilter').addEventListener('change',e=>{state.filters[name==='conversations'?'kind':'status']=e.target.value;state.pageNo=1;listing(name)})}
function changePage(delta){state.pageNo+=delta;listing(state.page)}
function closeModal(){$('#modal').classList.add('hidden')}$('#modal').addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeModal()});
function manageUser(raw){const user=JSON.parse(decodeURIComponent(raw));$('#modalCard').innerHTML=`<h3>Manage ${escapeHtml(user.full_name||user.username)}</h3><p>Change account access. Suspending or deleting will immediately revoke active sessions.</p><select id="userStatus"><option value="active" ${user.status==='active'?'selected':''}>Active</option><option value="suspended" ${user.status==='suspended'?'selected':''}>Suspended</option><option value="deleted" ${user.status==='deleted'?'selected':''}>Deleted</option></select><textarea id="statusReason" rows="3" placeholder="Reason for suspension (optional)"></textarea><div class="modal-actions"><button class="action-button" data-close>Cancel</button><button class="action-button primary-button" onclick="saveUserStatus('${user.id}')">Save change</button></div>`;$('#modal').classList.remove('hidden')}
async function saveUserStatus(id){try{await request(`/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status:$('#userStatus').value,reason:$('#statusReason').value.trim()})});closeModal();toast('User status updated');listing('users')}catch(error){toast(error.message)}}
function manageReport(raw){const report=JSON.parse(decodeURIComponent(raw));$('#modalCard').innerHTML=`<h3>Review safety report</h3><p><strong>${escapeHtml(report.reported_user)}</strong> was reported for ${escapeHtml(report.reason)}.</p><div class="privacy-banner">${escapeHtml(report.details||'No additional details provided.')}</div><select id="reportStatus"><option value="open" ${report.status==='open'?'selected':''}>Open</option><option value="reviewing" ${report.status==='reviewing'?'selected':''}>Reviewing</option><option value="resolved" ${report.status==='resolved'?'selected':''}>Resolved</option><option value="dismissed" ${report.status==='dismissed'?'selected':''}>Dismissed</option></select><div class="modal-actions"><button class="action-button" data-close>Cancel</button><button class="action-button primary-button" onclick="saveReport('${report.id}')">Update report</button></div>`;$('#modal').classList.remove('hidden')}
async function saveReport(id){try{await request(`/reports/${id}`,{method:'PATCH',body:JSON.stringify({status:$('#reportStatus').value})});closeModal();toast('Report updated');listing('reports')}catch(error){toast(error.message)}}
if(state.token)showApp();
