import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/groopx_ui.dart';
import '../../chat/data/chat_api.dart';
import '../../chat/domain/chat_models.dart';
import '../data/social_api.dart';

class ContactInfoScreen extends StatefulWidget{const ContactInfoScreen({super.key,required this.conversationId});final String conversationId;@override State<ContactInfoScreen> createState()=>_ContactInfoScreenState();}
class _ContactInfoScreenState extends State<ContactInfoScreen>{ConversationDetails? details;String? error;@override void initState(){super.initState();_load();}Future<void> _load()async{try{final value=await ChatApi.instance.conversation(widget.conversationId);if(mounted)setState(()=>details=value);}catch(_){if(mounted)setState(()=>error='Contact information load nahi hui.');}}
  @override Widget build(BuildContext context){final item=details;return Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:const Text('Contact Info')),body:GroopXBackground(child:item==null?(error==null?const Center(child:CircularProgressIndicator()):GroopXEmptyState(icon:Icons.cloud_off_outlined,title:'Unable to load',message:error!,actionLabel:'Retry',actionIcon:Icons.refresh,onAction:_load)):ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(children:[GroopXAvatar(label:item.title,imageUrl:item.avatarUrl,radius:48),const SizedBox(height:14),Text(item.title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(item.online?'Online':'Private GroopX contact',style:TextStyle(color:item.online?Colors.green:AppColors.muted))]))),const SizedBox(height:14),Row(children:[Expanded(child:_action(Icons.call_outlined,'Audio',()=>context.push('/call/audio/${widget.conversationId}'))),const SizedBox(width:10),Expanded(child:_action(Icons.videocam_outlined,'Video',()=>context.push('/call/video/${widget.conversationId}'))),const SizedBox(width:10),Expanded(child:_action(Icons.search,'Search',()=>context.push('/chat/${widget.conversationId}/search')))]),const SizedBox(height:14),Card(child:Column(children:[ListTile(leading:const Icon(Icons.perm_media_outlined,color:AppColors.purple),title:const Text('Media, links & documents'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/chat/${widget.conversationId}/media')),const Divider(height:1,indent:56),ListTile(leading:Icon(item.blockedByMe?Icons.person_add_alt:Icons.block,color:Colors.red),title:Text(item.blockedByMe?'Unblock contact':'Block contact',style:const TextStyle(color:Colors.red)),onTap:()async{final id=item.otherUserId;if(id==null)return;await SocialApi.instance.setBlocked(id,!item.blockedByMe);await _load();})]))])));}
  Widget _action(IconData icon,String label,VoidCallback tap)=>OutlinedButton(onPressed:tap,style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:14)),child:Column(children:[Icon(icon),const SizedBox(height:5),Text(label,style:const TextStyle(fontSize:11))]));
}
