import 'package:flutter/material.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/groopx_ui.dart';

class DataStorageScreen extends StatelessWidget{
  const DataStorageScreen({super.key});
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.background,appBar:AppBar(title:const Text('Storage & Data')),body:GroopXBackground(child:ListView(padding:const EdgeInsets.all(18),children:[const GroopXSectionTitle('Network usage'),const SizedBox(height:10),Card(child:Column(children:[_item(Icons.photo_outlined,'Photos','Uploaded in original supported format'),const Divider(height:1,indent:58),_item(Icons.movie_outlined,'Videos','Playback uses adaptive network streaming'),const Divider(height:1,indent:58),_item(Icons.description_outlined,'Documents','Files are stored securely in GroopX media storage')])),const SizedBox(height:22),const GroopXSectionTitle('Data protection'),const SizedBox(height:10),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.shield_outlined,color:AppColors.purple),SizedBox(width:10),Expanded(child:Text('Privacy-first media',style:TextStyle(fontWeight:FontWeight.w800)))]),const SizedBox(height:12),Text('Private chat media is accessible only through authenticated GroopX conversations. Signing out removes the secure session from this device.',style:TextStyle(color:AppColors.muted,height:1.5)),const SizedBox(height:12),Text('Local temporary files are managed automatically by Android and Flutter.',style:TextStyle(color:AppColors.muted,height:1.5))])))])));
  Widget _item(IconData icon,String title,String subtitle)=>ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:6),leading:Container(width:40,height:40,decoration:BoxDecoration(color:const Color(0xFFEEE9FF),borderRadius:BorderRadius.circular(12)),child:Icon(icon,color:AppColors.purple)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(subtitle));
}
